name: Docker image

on:
  release:
    types: [published]

jobs:
  publish-web:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling repo
        uses: actions/checkout@v1
      - name: Building latest image
        run: docker build cmd/web -t docker.pkg.github.com/$GITHUB_REPOSITORY/web
      - name: Adding additional tags
        run: |
          docker tag docker.pkg.github.com/$GITHUB_REPOSITORY/web docker.pkg.github.com/$GITHUB_REPOSITORY/web:$GITHUB_SHA
          docker tag docker.pkg.github.com/$GITHUB_REPOSITORY/web docker.pkg.github.com/$GITHUB_REPOSITORY/web:$(rev <<< $GITHUB_REF | cut -d/ -f1 | rev | tr -d v) 
      - name: Loging in
        run: docker login docker.pkg.github.com -u $(cut -d/ -f1 <<< $GITHUB_REPOSITORY) -p ${{ secrets.GITHUB_TOKEN }}
      - name: Pushing image
        run: |
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/web
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/web:$GITHUB_SHA
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/web:$(rev <<< $GITHUB_REF | cut -d/ -f1 | rev | tr -d v)
